# Generated by Django 5.0.7 on 2024-09-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
